packages:
  - packages/*
onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd
overrides:
  undici@>=4.5.0 <5.28.5: '>=5.28.5'
  esbuild@<=0.24.2: '>=0.25.0'
  axios@>=1.0.0 <1.8.2: '>=1.8.2'
  cookie@<0.7.0: '>=0.7.0'
  '@babel/runtime@<7.26.10': '>=7.26.10'
  '@babel/helpers@<7.26.10': '>=7.26.10'
  undici@<5.29.0: '>=5.29.0'
