packages:
  - packages/*

onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd

overrides:
  '@babel/helpers@<7.26.10': '>=7.26.10'
  '@babel/runtime@<7.26.10': '>=7.26.10'
  axios@>=1.0.0 <1.8.2: '>=1.8.2'
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  brace-expansion@>=2.0.0 <=2.0.1: '>=2.0.2'
  cookie@<0.7.0: '>=0.7.0'
  esbuild@<=0.24.2: '>=0.25.0'
  tar-fs@>=2.0.0 <2.1.3: '>=2.1.3'
  tmp@<=0.2.3: '>=0.2.4'
  undici@<5.29.0: '>=5.29.0'
  undici@>=4.5.0 <5.28.5: '>=5.28.5'
