export const ERROR_ID = {
	INVALID_PKG_NAME      : 'INVALID_PKG_NAME',
	GETTING_PKG_NAME      : 'GETTING_PKG_NAME',
	GETTING_REGISTRY_DATA : 'GETTING_REGISTRY_DATA',
	GETTING_LOCAL_DATA    : 'GETTING_LOCAL_DATA',
} as const

