###############################################################################
# RELEASE DOCS
###############################################################################

name: 🚀📚 Release Documentation

on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}
env:
    GITHUB_TOKEN: ${{ github.token }}
    DOCS_ID: 'sizium'
    DOCS_DIR: 'packages/docs/build/docs'
    BUILD_CMD: 'pnpm build'

###############################################################################
# JOBS
###############################################################################

jobs:
  deploy:
    runs-on: ubuntu-22.04
    env:
      UPDATED_VERSION: ${{ github.event.inputs.version }}

    steps:

      #########################################################################
      # INIT
      #########################################################################

      - name: ⬇️🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
      - name: ⬇️🛎 Checkout
        uses: actions/checkout@v4
      - name: ⬇️🥡 Install pnpm
        uses: pnpm/action-setup@v4
      - name: ⬇️🟢 Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: ⬇️📦 Install dependencies
        run: |
           export npm_config_build_from_source=false
           pnpm install --no-frozen-lockfile --ignore-scripts

      #########################################################################
      # BUILD
      #########################################################################

      - name: 🏗 Build packages
        run: ${{env.BUILD_CMD}}

      ###################################################################
      # BUILD AND DEPLOY
      ###################################################################

      - name: 🌥 Deploy in cloudflare pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          projectName: "${{env.DOCS_ID}}"
          directory: ${{env.DOCS_DIR}}
          wranglerVersion: '3'

###############################################################################
